<p><a href="user">Назад к профилю</a></p> 
<p><a href="cars/pres">Слайдшоу</a></p>


<?php
// module/Album/view/album/album/index.phtml:

$title = 'My cars';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if($this->zfcUserIdentity() && $this->zfcUserIdentity()->getRole() == 'admin') { ?>
<p>
    <a href="<?php echo $this->url('cars', array('action'=>'add'));?>">Add new car</a>
    
</p>
<?php } ?>

<table class="table">
<tr>
    <th>Photo</th>
    <th>Model</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($carss as $cars) : ?>
<tr>
    <td><?php echo "<img src='/img/" . $this->escapeHtml($cars->title) . "' />";?></td>
    <td><?php echo $this->escapeHtml($cars->artist);?></td>

    <?php if($this->zfcUserIdentity() && $this->zfcUserIdentity()->getRole() == 'admin') { ?>
        <td>
            <a href="<?php echo $this->url('cars',
                array('action'=>'edit', 'id' => $cars->id));?>">Edit</a>
            <a href="<?php echo $this->url('cars',
                array('action'=>'delete', 'id' => $cars->id));?>">Delete</a>
        </td>
    <?php } ?>
</tr>
<?php endforeach; ?>
</table>







