<?php if(!$this->zfcUserIdentity()) { ?>

<div style="background: white; border: 0px solid silver; padding: 5px; text-align: center; width: 1024px; " >
<marquee height="500"  scrollamount="5" width="400" direction="up">
<table class="table">

<?php foreach ($carss as $cars) : ?>
<tr><td><?php echo "<img src='/img/" . $this->escapeHtml($cars->title) . "' />";?></td></tr>
<tr><td><?php echo $this->escapeHtml($cars->artist);?></td></tr>
<?php endforeach; ?>
</table>

</marquee></div>

<?php } else { ?>

<div style="background: white; border: 0px solid silver; padding: 5px; text-align: center; width: 1024px; " >
<marquee height="500"  scrollamount="5" width="400" direction="up">
<table class="table">

<?php foreach ($carss as $cars) : ?>
<tr><td><?php echo "<img src='/img/" . $this->escapeHtml($cars->title) . "' />";?></td></tr>
<tr><td><?php echo $this->escapeHtml($cars->artist);?></td></tr>
<?php endforeach; ?>
</table>

</marquee></div>
<?php } ?>

