<?php if(!$this->zfcUserIdentity()) { ?>

<table>  

<tr><td>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/img/1.jpg" alt="GTR">
      <div class="carousel-caption">
        Nissan GTR
      </div>
    </div>
    <div class="item">
      <img src="/img/2.jpg" alt="Mersedes AMG">
      <div class="carousel-caption">
        Mersedes AMG
      </div>
    </div>
    <div class="item">
      <img src="/img/3.jpg" alt="WRX">
      <div class="carousel-caption">
        Subaru Impreza WRX STI
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</td></tr>

</table>

<?php } else { ?>

<table>  

<tr><td>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/img/1.jpg" alt="GTR">
      <div class="carousel-caption">
        Nissan GTR
      </div>
    </div>
    <div class="item">
      <img src="/img/2.jpg" alt="Mersedes AMG">
      <div class="carousel-caption">
        Mersedes AMG
      </div>
    </div>
    <div class="item">
      <img src="/img/3.jpg" alt="WRX">
      <div class="carousel-caption">
        Subaru Impreza WRX STI
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</td></tr>

</table> 
<?php } ?>

